INSERT INTO CERT_EXAM (EXAM_CENTER,CANDIDATE_EMAIL,EXAM_CODE,EXAM_NAME,EXAM_START_DATE_TIME,EXAM_PERCENTAGE,EXAM_RESULT,COUNTRY_CODE,RESERVATION_GUID)
VALUES ('TEST','TEST@TEST.COM','TESTCODE','JUNIT','2019-01-01',80,'Passed','CN','1111-1111-1111');
INSERT INTO USER_ROLE (EMAIL,USER_ROLE) VALUES ('TEST@TEST.COM','TESTER');